/// <reference lib="webworker" />
// src/sw.ts — compiled by Vite → public/sw.js
//
// Vite prepends: importScripts('/controller/controller.sw.js');
// controller.sw.js registers its own install (skipWaiting) and activate
// (clients.claim) listeners — we add to those, not replace them.

declare const self: ServiceWorkerGlobalScope;
declare const $scramjetController: {
  shouldRoute: (event: FetchEvent) => boolean;
  route:       (event: FetchEvent) => Promise<Response>;
};

const CACHE = "staticjet-v1";

// Stable small files that are safe to pre-cache at install time.
// Large files (scramjet.js, .wasm) are cached lazily on first fetch so a
// slow download can't block the SW install and leave nothing cached.
const SHELL = [
  "/",
  "/manifest.json",
  "/icons/favicon.png",
  "/icons/icon-192.png",
  "/icons/icon-512.png",
  "/icons/apple-touch-icon.png",
];

// ── Install — pre-cache shell + all Next.js chunks ───────────────────────────
// Uses individual fetches (non-atomic) so a single failure never wipes the
// whole cache. The hashed Next.js chunks come from precache-manifest.json
// which is generated by scripts/generate-precache.js after `next build`.
self.addEventListener("install", (e) => {
  e.waitUntil(
    (async () => {
      const cache = await caches.open(CACHE);

      // 1. Shell files — non-atomic, best effort
      await Promise.all(
        SHELL.map((url) =>
          fetch(url)
            .then((r) => { if (r.ok) cache.put(url, r); })
            .catch(() => {})
        )
      );

      // 2. Next.js hashed chunks from the build-time manifest
      try {
        const res = await fetch("/precache-manifest.json");
        if (res.ok) {
          const { urls } = (await res.json()) as { urls: string[] };
          await Promise.all(
            urls.map((url) =>
              fetch(url)
                .then((r) => { if (r.ok) cache.put(url, r); })
                .catch(() => {})
            )
          );
        }
      } catch { /* manifest not present yet — first build */ }

      // 3. Large scramjet assets — non-atomic, best effort
      const large = [
        "/scramjet/scramjet.js",
        "/scramjet/scramjet.wasm",
        "/controller/controller.api.js",
        "/controller/controller.sw.js",
        "/controller/controller.inject.js",
      ];
      await Promise.all(
        large.map((url) =>
          fetch(url)
            .then((r) => { if (r.ok) cache.put(url, r); })
            .catch(() => {})
        )
      );
    })()
  );
});

// ── Activate — evict stale caches ────────────────────────────────────────────
self.addEventListener("activate", (e) => {
  e.waitUntil(
    caches.keys().then((keys) =>
      Promise.all(keys.filter((k) => k !== CACHE).map((k) => caches.delete(k)))
    )
  );
});

// ── Fetch ─────────────────────────────────────────────────────────────────────
self.addEventListener("fetch", (e) => {
  // 1. Proxy traffic → Scramjet
  if ($scramjetController.shouldRoute(e)) {
    e.respondWith($scramjetController.route(e));
    return;
  }

  if (e.request.method !== "GET") return;
  const url = new URL(e.request.url);
  if (url.origin !== self.location.origin) return;

  // 2. Hashed Next.js chunks — immutable, cache-first forever
  if (url.pathname.startsWith("/_next/static/")) {
    e.respondWith(
      caches.match(e.request).then((hit) => {
        if (hit) return hit;
        return fetch(e.request).then((res) => {
          if (res.ok) {
            const clone = res.clone();
            caches.open(CACHE).then((c) => c.put(e.request, clone));
          }
          return res;
        });
      })
    );
    return;
  }

  // 3. Everything else — network-first, cache fallback for offline
  e.respondWith(
    fetch(e.request)
      .then((res) => {
        if (res.ok) {
          const clone = res.clone();
          caches.open(CACHE).then((c) => c.put(e.request, clone));
        }
        return res;
      })
      .catch(() =>
        caches.match(e.request).then(
          (hit) => hit ?? new Response("Static Jet — offline", { status: 503 })
        )
      )
  );
});
